In [1]:
import sys, os
sys.path.append(os.path.abspath('..'))
import pandas as pd

books = pd.read_csv('../data/lake/bronze/books.csv')
customers = pd.read_csv('../data/lake/bronze/customers.csv')
orders = pd.read_csv('../data/lake/bronze/orders.csv')
reviews = pd.read_csv('../data/lake/bronze/reviews.csv')

print('books   ', books.shape)
print('customers', customers.shape)
print('orders  ', orders.shape)
print('reviews ', reviews.shape)
display(books.head(3))
display(customers.head(3))
display(orders.head(3))
display(reviews.head(3))

books    (1000, 8)
customers (515, 7)
orders   (3060, 5)
reviews  (1200, 6)

,book_id,title,category,price_raw,rating_raw,availability,url,ingested_at
0,its-only-the-himalayas_981,It's Only the Himalayas,Travel,£45.17,Two,In stock,https://books.toscrape.com/catalogue/its-only-...,2026-10-27T07:43:25.942438+00:00
1,full-moon-over-noahs-ark-an-odyssey-to-mount-a...,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,£49.43,Four,In stock,https://books.toscrape.com/catalogue/full-moon...,2026-10-27T07:43:25.942438+00:00
2,see-america-a-celebration-of-our-national-park...,See America: A Celebration of Our National Par...,Travel,£48.87,Three,In stock,https://books.toscrape.com/catalogue/see-ameri...,2026-10-27T07:43:25.942438+00:00

,customer_id,full_name,email,phone,mykad,state,signup_date
0,C0192,Amir bin Salleh,amir.salleh70@yahoo.com,016-1230559,701103-01-9892,Johor,2025-01-22
1,C0252,Arjun a/l Rajan,arjun.rajan26@yahoo.com,0185654491,710419-08-2663,Perak,2024-07-22
2,C0441,Aisyah binti Abdullah,aisyah.abdullah71@gmail.com,0149066419,640511-08-0569,Perak,2025-03-24

  order_id customer_id                        book_id  quantity  order_date
0   O00001       C0141                the-republic_78         2  2026-03-02
1   O00002       C0344  the-nanny-diaries-nanny-1_265         2  2026-05-10
2   O00003       C0030            i-will-find-you_524         1  2026-05-28

,review_id,customer_id,book_id,stars,review_text,review_date
0,R00001,C0221,the-art-book_490,1,Nicely wrapped with bubble wrap.,2026-02-19
1,R00002,C0062,tuesday-nights-in-1980_870,2,"Barang sampai lambat, hampir tiga minggu.",2026-01-26
2,R00003,C0153,we-love-you-charlie-freeman_954,2,Pages were bent and the box was crushed.,2026-05-30